name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos:
    name: macOS (Swift 6.2)
    runs-on: macos-26
    timeout-minutes: 10
    strategy:
      matrix:
        xcode: ["26.0"]
        config: ["debug", "release"]
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Run ${{ matrix.config }} tests
        run: swift test -c ${{ matrix.config }} --enable-all-traits

  linux-61:
    name: Linux (Swift 6.1)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container: swift:6.1
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: swift test --traits SwiftOperationLogging

  linux:
    name: Linux (Swift 6.2)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container: swift:6.2
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: swift test --traits SwiftOperationLogging

  android:
    name: Android (Swift 6.2)
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: "Build Swift Package on Android"
        uses: swift-android-sdk/swift-android-action@v2
        with:
          swift-version: 6.2
          swift-build-flags: --traits SwiftOperationLogging
          run-tests: false

  windows:
    name: Windows (Swift 6.2)
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: "Setup Swift on Windows"
        uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-6.2-release
          tag: 6.2-RELEASE
      - name: "Build Swift Package on Windows"
        run: swift build --target Operation --traits SwiftOperationLogging

  wasm:
    name: WASM (Swift 6.1)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bytecodealliance/actions/wasmtime/setup@v1
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install Swift and Swift SDK for WebAssembly
        run: |
          PREFIX=/opt/swift
          set -ex
          curl -f -o /tmp/swift.tar.gz "https://download.swift.org/swift-6.1-release/ubuntu2204/swift-6.1-RELEASE/swift-6.1-RELEASE-ubuntu22.04.tar.gz"
          sudo mkdir -p $PREFIX; sudo tar -xzf /tmp/swift.tar.gz -C $PREFIX --strip-component 1
          $PREFIX/usr/bin/swift sdk install https://github.com/swiftwasm/swift/releases/download/swift-wasm-6.1-RELEASE/swift-wasm-6.1-RELEASE-wasm32-unknown-wasi.artifactbundle.zip --checksum 7550b4c77a55f4b637c376f5d192f297fe185607003a6212ad608276928db992
          echo "$PREFIX/usr/bin" >> $GITHUB_PATH
      - name: Install Playwright
        run: npm install playwright && npx playwright install chromium
      - name: Run tests
        run: ./test-wasm.sh
